# Generated by Django 4.2.3 on 2023-07-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_course_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('course', models.ManyToManyField(to='learn.course')),
            ],
        ),
    ]
