"""
Django settings for myweb project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^uk=qf1(^o81t4&9092t_lw8u#%39vtmf6v!oc%1+d2=(s_qt-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

ALLOWED_HOSTS = ["*",]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 添加的 learn 应用
    'learn',
    # 添加的 front 应用
    'front',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 防止跨域伪造攻击
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
        'DIRS': ['myweb/templates'],    # 这一行被修改,指定模板文件位置
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myweb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#原始默认的sqlite3的配置信息
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}
# 以下修改为本机环境的 MySQL 的配置
# 修改后
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',   # 指定连接数据库的引擎
        'NAME': 'myweb',                        # 指定连接的数据库
        'USER': 'root',                         # 数据库的账户
        'PASSWORD': 'root',                     # 账户的密码
        # 'PASSWORD': os.environ.get('MYSQL_PWD'), # 从系统环境变量中获取密码
        'HOST': '127.0.0.1',                    # 数据库的 IP 地址
        'PORT': 3306                            # 数据库的端口号
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# STATIC_URL = 'static/'
# 项目创建时默认生成的配置项，这是浏览器直接打开静态文件用的前缀目录
# 此种设置，默认会在web项目中含有当前项目（如：front、learn）中查找静态资源
STATIC_URL = 'static/'
# 如果是下面的设置，所有的静态资源均会到 项目（myweb）目录下的静态资源文件夹中查找
#STATIC_URL = '/static/'

# 静态文件放在对应的 app 下的 static 目录中或者 STATICFILES_DIRS 列表里的目录中
# 当 DEBUG = True 时，Django 就能自动找到放在里面的静态文件
# 如果不想用 STATICFILES_DIRS 可以不用，都放在 app 的 static 目录下也可以
STATICFILES_DIRS = ['myweb/static']

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
